packages:
  - 'apps/*'
  - 'packages/*'
  - 'frontend'
  - 'backend'
allowBuilds:
  '@nestjs/core': false
  '@prisma/engines': false
  bcrypt: false
  prisma: false
  sharp: false
  unrs-resolver: false
